### ISSUE TITLE
[Refactor]: 예외 처리 리팩토링

### ISSUE THREAD

**Issue by yonghyeonpark** [Seoul-NolGoat/be-seoul-nolgoat#26]
### 📋 개요

현재 특정 예외마다 커스텀 예외를 구현해 놓은 상태입니다. 그러나 확장성을 고려하여 소수의 커스텀 예외로 통합하고, 에러 코드 중심으로 예외를 관리하려고 합니다.

### ✔️ ToDo

- [x] 커스텀 예외를 줄이고 에러 코드로 예외를 관리
- [x] 에러 응답 Dto 수정
- [x] BindingResult 사용 대신 예외를 받아서 처리
