### ISSUE TITLE
[Refactor]: JWT 관련 로직 및 인증 리팩토링

### ISSUE THREAD

**Issue by yonghyeonpark** [Seoul-NolGoat/be-seoul-nolgoat#28]
### 📋 개요

현재 Refresh, Access 토큰 모두 헤더를 통해 전달받고 있는데, 보안 문제 해결을 위해 Refresh 토큰은 쿠키로 받도록 수정하고, 토큰 검증 로직이 좀 더 깔끔하게 진행되도록 하려 합니다. 추가로, 테스트용 토큰을 발급해 주는 기능도 구현하려 합니다.
인증 과정에서 발생하는 예외 처리가 어색하거나 잘못된 부분들이 있는데(ex - 토큰 만료 예외가 인증이 필요 없는 요청에서도 발생하는 상황, 의도한 예외가 제대로 발생하지 않는 상황), 해당 부분들을 자연스럽게 수정하려 합니다. 

### ✔️ ToDo

- [x] Refresh 토큰은 쿠키로 관리하도록 수정
- [x] 토큰 검증 로직을 깔끔하게 수정
- [x] 테스트용 토큰 발급 기능 구현
- [x] 인증 실패에 대해 자연스럽게 처리하도록 수정
