### ISSUE TITLE
[Feature]: 놀곳 파티 기능 추가

### ISSUE THREAD

**Issue by yonghyeonpark** [Seoul-NolGoat/be-seoul-nolgoat#31]
### 📋 개요

함께 놀곳을 즐기기 위해 파티를 생성하고, 해당 파티에 다른 유저들이 참여할 수 있는 기능을 구현합니다.

### ✔️ ToDo

- [x] 파티를 유저(생성자, 참여자)와 연관관계 매핑
- [x] 파티 생성, 참여 등 기능 구현
- [x] 파티 참여 시, 동시성 제어를 위한 락 설정
- [x] 테스트 코드 작성
