### ISSUE TITLE
[Refactor]: 공지 사항과 건의 사항 정렬 및 페이징 처리, 검증 강화, 로직 개선

### ISSUE THREAD

**Issue by yonghyeonpark** [Seoul-NolGoat/be-seoul-nolgoat#66]
### 📋 개요

현재 `공지 사항`과 `건의 사항` 기능에서 누락된 부분과 개선할 점이 있어, 이를 수정하고자 합니다.

### ✔️ ToDo

- [x] `공지 사항`과 `건의 사항`을 `최신순`으로 정렬하고, `페이징` 처리
- [x] `Bean Validation` 적용 및 검증 로직 추가
- [ ] ~`조회수 증가` 로직을 `조회` 로직에 통합~
