### ISSUE TITLE
[Refactor]: 파티 기능 마무리

### ISSUE THREAD

**Issue by yonghyeonpark** [Seoul-NolGoat/be-seoul-nolgoat#67]
### 📋 개요

미완성이던 `파티` 기능을 마무리하고자 합니다.

### ✔️ ToDo

- [x] `파티` 생성 및 참여 시, `마감일 검증` 로직 추가
- [x] `파티` 삭제 시, `S3` 삭제 로직 추가
- [x] `Bean Validation` 적용
- [ ] ~`파티`의 `가게` 필드를 `String`으로 적용~<br>=> 가게 지정 X
- [x] `지역`은 `Enum`으로 관리 (ex - `~구, ~동`)
- [ ] ~`카테고리`는 `String`으로 적용~<br>=> 카테고리 지정 X
